# Test: Uses development docker-file and a test-runner in the api/command

version: '3.5'
services:
  postgres:
    restart: always
    image: postgres:10.3
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    ports:
      - '5435:5432'

  api:
    build: 
      context: .
      dockerfile: container/dev.Dockerfile
    ports:
      - '3999:4000'
    env_file:
      - api/.env
    environment: 
      DB_STRING: 'postgresql://prisma:prisma@postgres:5432/postgres?schema=public'
    volumes:
        - './api/src:/app/src'
    depends_on: 
      - postgres
    command: sh -c 'npx prisma migrate up --experimental && (npx ts-node src/scripts/seed-db.ts) && (npx tsnd --exit-child --transpile-only -- ./src/app.ts)'