const language = {
  en: {
    general: {
      about: 'About',
      about_helper: 'About',
      branding: 'Branding',
      branding_color: 'Branding color',
      name: 'Name',
      first_name: 'First Name',
      first_name_helper: 'What is the user\'s first name?',
      last_name: 'Last name',
      last_name_helper: 'What is the user\'s last name?',
      email: 'Email adress',
      email_helper: 'What is the user\'s email adress?',
      phone: 'Phone number',
      phone_helper: 'What is the user\'s phone number? (Note: Start with country code, e.g. +316123456)',
      name_helper: 'What is the name of the business?',
      role_selector: 'User role',
      role_selector_helper: 'What will be the user\'s role?',
      slug: 'Url Extension',
      slug_helper: 'Under which url segment will visitors find the business?',
      template: 'Template',
    },
    customer: {
      about_helper: 'Please tell us a bit about the business, such as under which name and URL we can find it.',
      branding_color_helper: 'What is the main brand color of the company?',
      branding_helper: 'Describe the branding of your company, including logo and color',
      name_helper: 'What is the name of the business?',
      slug_helper: 'Under which url segment will visitors find the business?',
      use_template: 'Use template',
      use_template_helper: 'Start the onboarding with a pre-existing template, or start clean.',
      template_helper: 'Choose whether you have a preference what to start with.',
      custom_template: 'Custom template',
      custom_template_helper: 'Start with a default dialogue',
      no_custom_template: 'Fresh start',
      no_custom_template_helper: 'Start with a clean slate',
    },
    views: {
      edit_dialogue_view: 'Edit dialogue',
      edit_trigger_view: 'Edit trigger',
      dialogue_view: 'Overview',
      cta_view: 'Call to actions',
      builder_view: 'Dialogue Builder',
      interactions_view: 'Interactions',
      trigger_overview: 'Triggers',
      create_trigger_view: 'Create trigger',
    },
    dialogue: {
      slug_helper: 'Under which url segment will visitors find the dialogue?',
      qr_download_helper: 'Share the dialogue by sharing the QR code, by either downloading the QR code or copying it.',
    },
    trigger: {
      conditions: 'Conditions',
      conditions_helper: 'What are the conditions for sending out the trigger?',
      name_helper: 'What is the name of this trigger?',
      dialogue: 'Selected dialogue',
      dialogue_helper: 'To which dialogue will this trigger apply?',
      type: 'Type trigger',
      type_helper: 'What type of trigger is this?',
      delivery: 'Delivery',
      low_threshold: 'Low Threshold',
      low_threshold_helper: 'Set a low threshold: if a score is recorded underneath, a trigger will be sent',
      high_threshold: 'High Threshold',
      high_threshold_helper: 'Set a top-threshold: if a score is recorded over, a trigger will be sent',
      delivery_helper: 'How will this trigger be delivered to the recipients (mail or SMS)?',
      medium: 'Delivery medium',
      medium_helper: 'Which delivery method is preferred for this trigger? Note: additional costs may be incurred for SMS',
      question: 'Selected question',
      question_helper: 'Which question will the trigger be watching?',
      condition: 'Condition type',
      condition_helper: 'Which condition should apply to the trigger for this question to the currently selected question?',
      recipients: 'Recipients',
      recipients_helper: 'Who will receive these trigger alerts?',
      recipient: 'Recipient',
      recipient_helper: 'Select a registered user to be the receiver',
      match_text: 'Text to match',
      match_text_helper: 'What text should be matched to trigger the alert?',
    },
  },
};

export default language;
