export const OptionsOfPermissions = [
    {
            value:"CAN_ACCESS_ADMIN_PANEL",
            label:"CAN_ACCESS_ADMIN_PANEL",
            key:"CAN_ACCESS_ADMIN_PANEL",
            domain:"VIEW"
        },
    {
            value:"CAN_ADD_USERS",
            label:"CAN_ADD_USERS",
            key:"CAN_ADD_USERS",
            domain:"CREATE"
        },
    {
            value:"CAN_BUILD_DIALOGUE",
            label:"CAN_BUILD_DIALOGUE",
            key:"CAN_BUILD_DIALOGUE",
            domain:"CREATE"
        },
    {
            value:"CAN_CREATE_TRIGGERS",
            label:"CAN_CREATE_TRIGGERS",
            key:"CAN_CREATE_TRIGGERS",
            domain:"CREATE"
        },
    {
            value:"CAN_DELETE_TRIGGERS",
            label:"CAN_DELETE_TRIGGERS",
            key:"CAN_DELETE_TRIGGERS",
            domain:"DELETE"
        },
    {
            value:"CAN_DELETE_USERS",
            label:"CAN_DELETE_USERS",
            key:"CAN_DELETE_USERS",
            domain:"DELETE"
        },
    {
            value:"CAN_DELETE_WORKSPACE",
            label:"CAN_DELETE_WORKSPACE",
            key:"CAN_DELETE_WORKSPACE",
            domain:"DELETE"
        },
    {
            value:"CAN_EDIT_DIALOGUE",
            label:"CAN_EDIT_DIALOGUE",
            key:"CAN_EDIT_DIALOGUE",
            domain:"Edit"
        },
    {
            value:"CAN_EDIT_USERS",
            label:"CAN_EDIT_USERS",
            key:"CAN_EDIT_USERS",
            domain:"Edit"
        },
    {
            value:"CAN_EDIT_WORKSPACE",
            label:"CAN_EDIT_WORKSPACE",
            key:"CAN_EDIT_WORKSPACE",
            domain:"Edit"
        },
        {
            value:"CAN_VIEW_DIALOGUE",
            label:"CAN_VIEW_DIALOGUE",
            key:"CAN_VIEW_DIALOGUE",
            domain:"VIEW"
        },
        {
            value:"CAN_VIEW_DIALOGUE_ANALYTICS",
            label:"CAN_VIEW_DIALOGUE_ANALYTICS",
            key:"CAN_VIEW_DIALOGUE_ANALYTICS",
            domain:"VIEW"
        },
        {
            value:"CAN_VIEW_USERS",
            label:"CAN_VIEW_USERS",
            key:"CAN_VIEW_USERS",
            domain:"VIEW"
        },
        {
            value:"CAN_VIEW_CAMPAIGNS",
            label:"CAN_VIEW_CAMPAIGNS",
            key:"CAN_VIEW_CAMPAIGNS",
            domain:"VIEW"
        },
        {
            value:"CAN_CREATE_CAMPAIGNS",
            label:"CAN_CREATE_CAMPAIGNS",
            key:"CAN_CREATE_CAMPAIGNS",
            domain:"CREATE"
        },
        {
            value:"CAN_CREATE_DELIVERIES",
            label:"CAN_CREATE_DELIVERIES",
            key:"CAN_CREATE_DELIVERIES",
            domain:"CREATE"
        },
    ]