
import { LanguageEnum, NodeType } from '@prisma/client';
import { defaultAdminRole, defaultBotRole, defaultBusinessTextFieldForm, defaultManagerRole, defaultUserRole, DemoWorkspaceTemplate } from './TemplateTypes';

export type rootTopics = 'Physical & Mental' | 'Management' | 'Home Situation' | 'Colleagues'
  | 'Performance' | 'Work Pressure';

const businessOptions = [
  { value: 'Physical & Mental', position: 1 },
  { value: 'Management', position: 2 },
  { value: 'Home Situation', position: 3 },
  { value: 'Colleagues', position: 4 },
  { value: 'Performance', position: 5 },
  { value: 'Work Pressure', position: 6 },
  { value: 'Company Leadership', position: 7 },
];

const businessWorkspaceTemplate: DemoWorkspaceTemplate = {
  structure: [
    {
      title: 'How are you feeling?',
      isRoot: true,
      type: NodeType.SLIDER,
      edge: null,
      options: [],
      children: [
        {
          title: 'What\'s going well?',
          topic: {
            name: 'VERY_POSITIVE',
          },
          type: NodeType.CHOICE,
          edge: {
            conditionType: 'valueBoundary',
            matchValue: null,
            renderMin: 70,
            renderMax: 100,
          },
          options: businessOptions,
          cta: null,
        },
        {
          title: 'You\'re not completely satisfied. What can be improved?',
          topic: {
            name: 'POSITIVE',
          },
          type: NodeType.CHOICE,
          edge: {
            conditionType: 'valueBoundary',
            matchValue: null,
            renderMin: 55,
            renderMax: 70,
          },
          options: businessOptions,
          cta: null,
        },
        {
          title: 'That\'s unfortunate! What went wrong?',
          topic: {
            name: 'NEGATIVE',
          },
          type: NodeType.CHOICE,
          edge: {
            conditionType: 'valueBoundary',
            matchValue: null,
            renderMin: 25,
            renderMax: 55,
          },
          options: businessOptions,
          cta: 'ContactFormNode',
        },
        {
          title: 'That\'s unfortunate! What went wrong?',
          topic: {
            name: 'VERY_NEGATIVE',
          },
          type: NodeType.CHOICE,
          edge: {
            conditionType: 'valueBoundary',
            matchValue: null,
            renderMin: 0,
            renderMax: 25,
          },
          options: businessOptions,
          cta: 'ContactFormNode',
        },
      ],
    },
  ],
  title: 'How do you feel about us?',
  slug: 'business',
  language: LanguageEnum.ENGLISH,
  rootLayer: ['Amsterdam', 'London'],
  subLayer: ['Legal', 'Tax', 'M&A'],
  subSubLayer: ['Sales', 'Marketing', 'Consulting'],
  topics: {
    'Physical & Mental': [],
    'Management': [],
    'Home Situation': [],
    'Colleagues': [],
    'Performance': [],
    'Work Pressure': [],
  },
  description: 'This is a default dialogue generated by the Haas business template',
  primaryColor: '#667EEA',
  postLeafText: {
    header: 'Thank you for your input!',
    subHeader: 'Life should be fulfilling',
  },
  tags: [
    {
      name: 'Agent',
      type: 'AGENT',
    },
    {
      name: 'Amsterdam',
      type: 'LOCATION',
    },
    {
      name: 'Standard survey',
      type: 'DEFAULT',
    },
  ],
  roles: [
    defaultAdminRole,
    defaultManagerRole,
    defaultUserRole,
    defaultBotRole,
  ],
  rootSliderOptions: {
    markers: [
      {
        label: 'Good!',
        subLabel: 'I\'m feeling good.',
        range: { start: 6, end: 9.5 },
      },
      {
        label: 'Amazing!',
        subLabel: 'I\'m feeling amazing.',
        range: { start: 9.5 },
      },
      {
        label: 'Neutral!',
        subLabel: 'I could feel better.',
        range: { start: 5, end: 6 },
      },
      {
        label: 'Bad',
        subLabel: 'I\'m feeling bad.',
        range: { start: 3, end: 5 },
      },
      {
        label: 'Terrible',
        subLabel: 'I\'m feeling terrible.',
        range: { end: 3 },
      },
    ],
  },
  leafNodes: [
    {
      leafMatchId: 'ContactFormNode',
      title:
        'Your feedback will always remain anonymous, unless you want to talk to someone.',
      type: NodeType.FORM,
      form: defaultBusinessTextFieldForm,
    },
  ],
};

export default businessWorkspaceTemplate;
