import { LanguageEnum, NodeType } from '@prisma/client';
import { defaultAdminRole, defaultBotRole, defaultBusinessTextFieldForm, defaultManagerRole, defaultUserRole, DemoWorkspaceTemplate } from './TemplateTypes';

export type rootTopics = 'Physical & Mental' | 'Management' | 'Home Situation' | 'Colleagues'
  | 'Performance' | 'Work Pressure';

const businessWorkspaceTemplate: DemoWorkspaceTemplate = {
  title: 'How do you feel about us?',
  slug: 'business',
  language: LanguageEnum.ENGLISH,
  rootLayer: ['Amsterdam', 'London'],
  subLayer: ['Legal', 'Tax', 'M&A'],
  subSubLayer: ['Sales', 'Marketing', 'Consulting'],
  topics: {
    'Physical & Mental': [],
    'Management': [],
    'Home Situation': [],
    'Colleagues': [],
    'Performance': [],
    'Work Pressure': [],
  },
  description: 'This is a default dialogue generated by the Haas business template',
  primaryColor: '#667EEA',
  postLeafText: {
    header: 'Thank you for your input!',
    subHeader: 'Life should be fulfilling',
  },
  tags: [
    {
      name: 'Agent',
      type: 'AGENT',
    },
    {
      name: 'Amsterdam',
      type: 'LOCATION',
    },
    {
      name: 'Standard survey',
      type: 'DEFAULT',
    },
  ],
  roles: [
    defaultAdminRole,
    defaultManagerRole,
    defaultUserRole,
    defaultBotRole,
  ],
  rootSliderOptions: {
    markers: [
      {
        label: 'Good!',
        subLabel: 'I\'m feeling good.',
        range: { start: 6, end: 9.5 },
      },
      {
        label: 'Amazing!',
        subLabel: 'I\'m feeling amazing.',
        range: { start: 9.5 },
      },
      {
        label: 'Neutral!',
        subLabel: 'I could feel better.',
        range: { start: 5, end: 6 },
      },
      {
        label: 'Bad',
        subLabel: 'I\'m feeling bad.',
        range: { start: 3, end: 5 },
      },
      {
        label: 'Terrible',
        subLabel: 'I\'m feeling terrible.',
        range: { end: 3 },
      },
    ],
  },
  leafNodes: [
    // TODO: Give some sort of identifier so we know this is THE leaf we want to add as CTA to a question
    {
      title:
        'Your feedback will always remain anonymous, unless you want to talk to someone.',
      type: NodeType.FORM,
      form: defaultBusinessTextFieldForm,
    },
  ],
};

export default businessWorkspaceTemplate;
