import { NodeType, RoleCreateInput, TagEnum } from '@prisma/client';

interface Tag {
  name: string,
  type: TagEnum,
}

export interface WorkspaceTemplate {
  title: string;
  slug: string;
  topics: string[];
  description: string;
  primaryColor: string;
  leafNodes: any;
  roles: RoleCreateInput[];
  tags: Tag[];
}

const defaultLinks: any[] = [
  { url: 'https://facebook.com', type: 'FACEBOOK', backgroundColor: '#1877f2' },
  { url: 'https://twitter.com', type: 'TWITTER', backgroundColor: '#1da1f2' },
  { url: 'https://instagram.com', type: 'INSTAGRAM', backgroundColor: '#c32aa3' },
  { url: 'https://linkedin.com', type: 'LINKEDIN', backgroundColor: '#007bb5' },
];

const defaultWorkspaceTemplate: WorkspaceTemplate = {
  title: 'How do you feel about us?',
  slug: 'default',
  topics: ['Facilities', 'Website/Mobile app', 'Product/Services', 'Customer support'],
  description: 'This is a default dialogue generated by the Haas template',
  primaryColor: '#667EEA',
  tags: [
    {
      name: 'Agent',
      type: 'AGENT',
    },
    {
      name: 'Amsterdam',
      type: 'LOCATION',
    },
    {
      name: 'Standard survey',
      type: 'DEFAULT',
    },
  ],
  roles: [
    {
      name: 'Admin',
      type: 'ADMIN',
      isPrivate: true,
      permissions: {
        set: [
          'CAN_VIEW_USERS',
          'CAN_ADD_USERS',
          'CAN_BUILD_DIALOGUE',
          'CAN_CREATE_TRIGGERS',
          'CAN_DELETE_DIALOGUE',
          'CAN_DELETE_TRIGGERS',
          'CAN_EDIT_DIALOGUE',
          'CAN_EDIT_USERS',
          'CAN_DELETE_USERS',
          'CAN_DELETE_WORKSPACE',
          'CAN_EDIT_WORKSPACE',
          'CAN_VIEW_DIALOGUE',
          'CAN_VIEW_DIALOGUE_ANALYTICS',
        ],
      },
    },
    {
      name: 'Manager',
      type: 'MANAGER',
      permissions: {
        set: [
          'CAN_VIEW_USERS',
          'CAN_ADD_USERS',
          'CAN_BUILD_DIALOGUE',
          'CAN_CREATE_TRIGGERS',
          'CAN_DELETE_DIALOGUE',
          'CAN_DELETE_TRIGGERS',
          'CAN_EDIT_DIALOGUE',
          'CAN_EDIT_WORKSPACE',
          'CAN_VIEW_DIALOGUE',
          'CAN_VIEW_DIALOGUE_ANALYTICS',
        ],
      },
      isPrivate: false,
    },
    {
      name: 'User',
      type: 'USER',
      permissions: {
        set: [
          'CAN_VIEW_DIALOGUE',
          'CAN_VIEW_DIALOGUE_ANALYTICS',
        ],
      },
    },
  ],
  leafNodes: [
    {
      title: 'We are happy about your positive feedback. If you wish to let us know anything else, let us know below.',
      type: NodeType.TEXTBOX,
    },
    {
      title: 'Thank you for your elaborate feedback. Follow us on our social media.',
      type: NodeType.LINK,
      links: defaultLinks,
    },
    {
      title: 'Thank you for your feedback on our facilities. We hope to see you soon again!',
      type: NodeType.LINK,
      links: defaultLinks,
    },
    {
      title:
        'Thank you for your feedback on our website. We hope to hear from you again!',
      type: NodeType.LINK,
      links: defaultLinks,
    },
    {
      title:
        'Thank you for your positive feedback. Follow us on Instagram and stay updated.',
      type: NodeType.LINK,
      links: defaultLinks,
    },
    {
      title:
        'Thank you for your positive feedback. Come and join us on 1st April for our great event. Leave your email address below to register.',
      type: NodeType.REGISTRATION,
      links: [],
    },
    {
      title:
        'Thank you for your feedback. Would you like to say anything else?',
      type: NodeType.TEXTBOX,
      links: [],
    },
    {
      title:
        'We are happy about your positive feedback. You matter to us! Leave your email below to receive our newsletter.',
      type: NodeType.REGISTRATION,
      links: [],
    },
    {
      title:
        'Thank you for your feedback. You matter to us! Leave your email below to receive our newsletter.',
      type: NodeType.REGISTRATION,
      links: [],
    },
    {
      title: 'Thank you! Leave your email below to subscribe to our newsletter.',
      type: NodeType.REGISTRATION,
      links: [],
    },
    {
      title:
        'Thank you for your feedback. Our customer experience supervisor is informed. Please leave your email below so we can solve the issue.',
      type: NodeType.REGISTRATION,
      links: [],
    },
    {
      title:
        'Thank you for your feedback. You matter to us! Click below for your refund.',
      type: NodeType.REGISTRATION,
      links: [],
    },
    {
      title:
        'Thank you for your feedback. Please click on the Whatsapp link below so our service team can fix the issue.',
      type: NodeType.REGISTRATION,
      links: [],
    },
    {
      title:
        'Thank you for your feedback. Our team is on it. If you leave your email below we will keep you updated.',
      type: NodeType.REGISTRATION,
      links: [],
    },
    {
      title:
        'Thank you! Please leave your contact details below so we can reach out to you with a solution.',
      type: NodeType.REGISTRATION,
      links: [],
    },
  ],
};

export default defaultWorkspaceTemplate;
