import { LanguageEnum, NodeType } from '@prisma/client';
import WorkspaceTemplate, { defaultAdminRole, defaultBotRole, defaultForm, defaultManagerRole, defaultUserRole, DemoWorkspaceTemplate } from './TemplateTypes';

const sportWorkspaceTemplate: DemoWorkspaceTemplate = {
  title: 'How do you feel about us?',
  slug: 'sport',
  language: LanguageEnum.DUTCH,
  rootLayer: ['Jongens', 'Meisjes'],
  subLayer: ['O8', 'O12', 'O16', 'O18'],
  subSubLayer: ['Team1', 'Team2', 'Team3'],
  topics: {
    'Lichaam & Geest': [],
    'Begeleiding': [],
    'Thuis': [],
    'School': [],
    'Teamgenoten': [],
    'Eigen Prestatie': [],
  },
  description: 'This is a default dialogue generated by the Haas sport NL template',
  primaryColor: '#667EEA',
  tags: [
    {
      name: 'Agent',
      type: 'AGENT',
    },
    {
      name: 'Amsterdam',
      type: 'LOCATION',
    },
    {
      name: 'Standard survey',
      type: 'DEFAULT',
    },
  ],
  roles: [
    defaultAdminRole,
    defaultManagerRole,
    defaultUserRole,
    defaultBotRole,
  ],
  rootSliderOptions: {
    unhappyText: 'Slecht',
    happyText: 'Goed',
    markers: [
      {
        label: 'Goed!',
        subLabel: 'Ik voel me goed.',
        range: { start: 6, end: 9.5 },
      },
      {
        label: 'Geweldig!',
        subLabel: 'Ik voel me geweldig.',
        range: { start: 9.5 },
      },
      {
        label: 'Neutraal!',
        subLabel: 'Ik voel me oke.',
        range: { start: 5, end: 6 },
      },
      {
        label: 'Slecht',
        subLabel: 'Ik voel me slecht.',
        range: { start: 3, end: 5 },
      },
      {
        label: 'Heel slecht',
        subLabel: 'Ik voel me heel slecht.',
        range: { end: 3 },
      },
    ],
  },
  postLeafText: {
    header: 'Dankjewel voor je feedback!',
    subHeader: 'Werk moet voldoening geven',
  },
  leafNodes: [
    {
      title:
        'Jouw feedback blijft altijd anoniem, tenzij je er met iemand over wil praten. Als je dat wil, laat dan je email en/of naam achter.',
      type: NodeType.FORM,
      form: defaultForm,
    },
  ],
};

export default sportWorkspaceTemplate;
