import { LanguageEnum, NodeType } from '@prisma/client';
import { defaultAdminRole, defaultBotRole, defaultManagerRole, defaultSportTextFieldForm, defaultUserRole, DemoWorkspaceTemplate } from './TemplateTypes';

const sportWorkspaceTemplate: DemoWorkspaceTemplate = {
  title: 'How do you feel about us?',
  slug: 'sport',
  language: LanguageEnum.ENGLISH,
  rootLayer: ['Male', 'Female'],
  subLayer: ['U8', 'U12', 'U16', 'U18'],
  subSubLayer: ['Team1', 'Team2', 'Team3'],
  topics: {
    'Physical & Mental': [],
    'Coaching': [],
    'Home': [],
    'School': [],
    'Team Members': [],
    'Own Performance': [],
  },
  description: 'This is a default dialogue generated by the Haas sport template',
  primaryColor: '#667EEA',
  tags: [
    {
      name: 'Agent',
      type: 'AGENT',
    },
    {
      name: 'Amsterdam',
      type: 'LOCATION',
    },
    {
      name: 'Standard survey',
      type: 'DEFAULT',
    },
  ],
  roles: [
    defaultAdminRole,
    defaultManagerRole,
    defaultUserRole,
    defaultBotRole,
  ],
  postLeafText: {
    header: 'Thank you for your input!',
    subHeader: 'Work should be fulfilling',
  },
  rootSliderOptions: {
    markers: [
      {
        label: 'Good!',
        subLabel: 'It\'s going well.',
        range: { start: 6, end: 9.5 },
      },
      {
        label: 'Amazing!',
        subLabel: 'It\'s going amazing.',
        range: { start: 9.5 },
      },
      {
        label: 'Neutral!',
        subLabel: 'It could be better.',
        range: { start: 5, end: 6 },
      },
      {
        label: 'Bad',
        subLabel: 'It\'s going bad.',
        range: { start: 3, end: 5 },
      },
      {
        label: 'Terrible',
        subLabel: 'It\'s going terrible.',
        range: { end: 3 },
      },
    ],
  },
  leafNodes: [
    {
      title:
        'Your feedback will always remain anonymous, unless you want to talk to someone.',
      type: NodeType.FORM,
      form: defaultSportTextFieldForm,
    },
  ],
};

export default sportWorkspaceTemplate;
