import { NodeType } from '@prisma/client';
import WorkspaceTemplate, { defaultAdminRole, defaultBotRole, defaultForm, defaultManagerRole, defaultUserRole } from './TemplateTypes';

export type rootTopics = 'Physical & Mental' | 'Management' | 'Home Situation' | 'Colleagues'
  | 'Performance' | 'Work Pressure'

const sportWorkspaceTemplate: WorkspaceTemplate = {
  title: 'How do you feel about us?',
  slug: 'sport',
  topics: ['Physical & Mental', 'Management', 'Home Situation', 'Colleagues', 'Performance', 'Work Pressure'],
  description: 'This is a default dialogue generated by the Haas business template',
  primaryColor: '#667EEA',
  tags: [
    {
      name: 'Agent',
      type: 'AGENT',
    },
    {
      name: 'Amsterdam',
      type: 'LOCATION',
    },
    {
      name: 'Standard survey',
      type: 'DEFAULT',
    },
  ],
  roles: [
    defaultAdminRole,
    defaultManagerRole,
    defaultUserRole,
    defaultBotRole,
  ],
  rootSliderOptions: {
    markers: [
      {
        label: 'Good!',
        subLabel: 'This is good.',
        range: { create: { start: 6, end: 9.5 } },
      },
      {
        label: 'Amazing!',
        subLabel: 'This is excellent.',
        range: { create: { start: 9.5 } },
      },
      {
        label: 'Neutral!',
        subLabel: 'Something is not great.',
        range: { create: { start: 5, end: 6 } },
      },
      {
        label: 'Bad',
        subLabel: 'This is bad.',
        range: { create: { start: 3, end: 5 } },
      },
      {
        label: 'Terrible',
        subLabel: 'This is terrible',
        range: { create: { end: 3 } },
      },
    ],
  },
  leafNodes: [
    {
      title:
        'Your feedback will always remain anonymous, unless you want to talk to someone. =>  Leave your name and someone from HR will contact you ⇣',
      type: NodeType.FORM,
      form: defaultForm,
    },
  ],
};

export default sportWorkspaceTemplate;
