import { NodeType } from '@prisma/client';
import WorkspaceTemplate, { defaultAdminRole, defaultBotRole, defaultForm, defaultManagerRole, defaultUserRole, DemoWorkspaceTemplate } from './TemplateTypes';

const sportWorkspaceTemplate: DemoWorkspaceTemplate = {
  title: 'How do you feel about us?',
  slug: 'sport',
  rootLayer: ['Jongens', 'Meisjes'],
  subLayer: ['O8', 'O12', 'O16', 'O18'],
  subSubLayer: ['Team1', 'Team2', 'Team3'],
  topics: ['Lichaam & Geest', 'Begeleiding', 'Thuis', 'School', 'Teamgenoten', 'Eigen Prestatie'],
  description: 'This is a default dialogue generated by the Haas sport NL template',
  primaryColor: '#667EEA',
  tags: [
    {
      name: 'Agent',
      type: 'AGENT',
    },
    {
      name: 'Amsterdam',
      type: 'LOCATION',
    },
    {
      name: 'Standard survey',
      type: 'DEFAULT',
    },
  ],
  roles: [
    defaultAdminRole,
    defaultManagerRole,
    defaultUserRole,
    defaultBotRole,
  ],
  rootSliderOptions: {
    markers: [
      {
        label: 'Goed!',
        subLabel: 'Dit is goed.',
        range: { create: { start: 6, end: 9.5 } },
      },
      {
        label: 'Geweldig!',
        subLabel: 'Dit is geweldig.',
        range: { create: { start: 9.5 } },
      },
      {
        label: 'Neutraal!',
        subLabel: 'Iets is niet helemaal okee.',
        range: { create: { start: 5, end: 6 } },
      },
      {
        label: 'Slecht',
        subLabel: 'Dit is slecht.',
        range: { create: { start: 3, end: 5 } },
      },
      {
        label: 'Verschrikkelijk',
        subLabel: 'Dit is verschrikkelijk.',
        range: { create: { end: 3 } },
      },
    ],
  },
  leafNodes: [
    {
      title:
        'Jouw feedback blijft altijd anoniem, tenzij je er met iemand over wil praten. Als je dat wil, laat dan je naam achter.',
      type: NodeType.FORM,
      form: defaultForm,
    },
  ],
};

export default sportWorkspaceTemplate;
