version: '3'
services:
  postgres:
    restart: always
    image: postgres:10.3
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - local-datavolume:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  redis:
    image: "redis:alpine"
    ports:
      - '6379:6379'
volumes:
  local-datavolume:
