version: '3'
services:
  tracing:
    image: jaegertracing/all-in-one:1.35
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
      COLLECTOR_ZIPKIN_HOST_PORT: ":9411"
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
  redis:
    image: 'redis:7.0.2'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6380:6379'
  postgres:
    restart: always
    image: postgres:12.2
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - local-datavolume:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  local-datavolume:
