version: '3.2'
services:
  api:
    build: .
    env_file: .env
    ports:
        - '4000:4000'
  postgres:
    restart: always
    image: postgres:10.3
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - local-datavolume:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  local-datavolume: