version: '3'
services:
  postgres:
    restart: always
    image: postgres:10.3
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    ports:
      - '5432:5432'
    networks:
      - test 
  api:
    build: .
    ports:
      - '4000:4000'
    env_file:
      - .env
    command: ['bash', './build/prep-database.sh', '&&' ,'yarn test']
    environment: 
      TEST_VAR: 'HELLO'
    networks:
      - test
    volumes:
        - './src:/app/src'
        - './build:/app/build'
networks: 
  test: