name: CI_PR
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run ESLint
      run: yarn eslint
    - name: Start Testing Containers
      run: dock:test:start-db
    - name: Run Unit and integration Tests
      run: yarn test:integration
